### ISSUE TITLE
Select on polarization strings

### ISSUE THREAD

**Issue by dstorer** [RadioAstronomySoftwareGroup/pyuvdata#1023]
UVData select only accepts polarization numbers and not polarization strings. It would be ideal to be able to use pol strings as well. For example:

`uv.select(polarizations='xx')`

**Comment by Zhilei** [comment]
Following up on this topic, I was wondering whether we can add a function to select polarization in the `north` and `east` space, instead of the instrumental `xx` (`-5`) and `yy` (`-6`) space.
I was advised that this can be wrapped around the `polstr2num` function, which considers the `x_orientation` attribute and assigns `xx`(`yy`) to `north`(`east`) accordingly.
This will be useful since the `x_orientation` points to `east` in H1C and switched to `north` for H2C+.

**Comment by Zhilei** [comment]
It will be great if this functionality can be added in pyuvbeam object as well
