### ISSUE TITLE
Handle `None` values in `extra_keywords` better when writing UVH5 files

### ISSUE THREAD

**Issue by plaplant** [RadioAstronomySoftwareGroup/pyuvdata#1081]
If the user has any keys in the `extra_keywords` dict that have a key of `None`, writing UVH5 files raises an error that doesn't make it obvious what is going wrong. We should either handle values of `None` in a better way, or give the user a better error message and a hint about how to fix it.

**Comment by bhazelton** [comment]
Digging into this more, the error that prompted this issue came from reading in an MWA meta fits file. The keyword that was None was the "DELAYMOD" keyword. Inspecting a metafits file, the comment associated with that keyword is "MWAX correlator delay mode". For non-MWA folks, the MWAX is the brand new correlator (just started taking data this week) which can do phasing internally. This is obviously an important keyword for MWAX data, but the file in question was taken earlier with the old correlator. They apparently added that keyword to all metafits files in preparation for MWAX coming online. 

My feeling is that that keyword can be dropped for data not taken with MWAX in the mwa_corr_fits reader. But before we implement this fully, I'd like to know what will be in that field for MWAX data (i.e. will it ever be empty for MWAX data?). @PyxieLouStar do you agree?

**Comment by plaplant** [comment]
Good to know, thanks. I have a local fix for correctly propagating `None` values through UVH5 files, so hopefully it's not a problem going forward. In local testing, `None` values are correctly propagated through UVFITS files, and it seems like an easy enough thing to add for UVH5. I'll write accompanying tests and make a formal PR soon.

**Comment by PyxieLouStar** [comment]
That sounds good. I'll take a look at the new MWAX metafits files and see what I find.
