### ISSUE TITLE
Frequency concatenation yields wrong data

### ISSUE THREAD

**Issue by wfarah** [RadioAstronomySoftwareGroup/pyuvdata#1102]
Using `pyuvdata==2.2.4`

I’m trying to concatenate `uvh5` files in frequency, and I’m simply using `uv = uv1 + uv2 + uv3 + ...`  then writing out `.ms` file and parsing it to `casa`. This worked perfectly well all the time I used it, except for now where I started seeing some weirdness. The phase of the autocorrelation for some of the subbands appeared to be non-zero, which is not expected.
What I’m doing is the following:
```
uv1.read("subband1.uvh5")
uv2.read("subband2.uvh5")
...
uv = uv1 + uv2 + ...
uv.write_ms()
uv.write_hdf5()
```

I then read the `ant_1_names` and `ant_2_names` from all the `uv` files, and I could see that the first integrations in the concatenated `uvfiles` are not the autocorrelations, unlike the subbands:
```
subband1.uvh5
[ 3  5  7 ... 33 33 35] #ant_1_names
[ 3  5  7 ... 35 38 38] #ant_2_names

subband2.uvh5
[ 3  5  7 ... 33 33 35]
[ 3  5  7 ... 35 38 38]

...

concatenated.uvh5
[ 3  3  3 ... 33 33 35] #something is wrong here
[ 3  5  7 ... 35 38 38]
```

These are some cross/auto correlations respectively, viewed in casa. I also extracted the visibilities straight from the uvh5 files, and I see the same thing
<img width="1413" alt="Screen Shot 2021-12-09 at 1 49 35 PM" src="https://user-images.githubusercontent.com/10710289/145481221-6c194b2c-3f18-4a89-9317-59fd8b191ae2.png">
<img width="1424" alt="Screen Shot 2021-12-09 at 1 49 47 PM" src="https://user-images.githubusercontent.com/10710289/145481250-91be83c9-a879-424b-88fb-66b6ae01893c.png">

**Comment by wfarah** [comment]
Data is available on google drive:

https://drive.google.com/drive/folders/1BzNo8fa2yeS8kbO7MoNSPY8pY1FS_j8U

**Comment by david-macmahon** [comment]
Does the baseline ordering vary between input datasets or are the `time_array`s from each input dataset not identical?  AFAIK, these input datasets should have all the same metadata *except* for the `freq_array`s (which should even be contiguous in frequency).  But it's not my data so I can't say for sure whether that's all true.

**Comment by kartographer** [comment]
@david-macmahon -- the ordering is in fact not different between them, but some files contain different subsets of times or baselines (my guess being the former), which causes `__add__` to effectively reorder them after concatenation. That resultant `UVData` object _does_ have a different ordering, which is why the subsequent adds effectively corrupt the data set.

**Comment by david-macmahon** [comment]
@kartographer, your guess is exactly right.  The first clue was that the file sizes are significantly different.  Further examination of the two `node1` UVH5 files show that the `*_0.uvh5` file contains 59 integrations and the `*_1.uvh5` file contains 54 integrations based on the `Header/Ntimes` value from each file.  The final `time_array` entries differ by 5 integration times (i.e. 59-54), so that nicely corroborates the mismatched time dimension (and therefore the mismatched Nblts dimension).

Not sure if this is originally caused by a "dropped/missing data" problem in the data capture code or mis-matched scan lengths between files.  If the former, then the software correlator code should be more robust to dropped/missing data (and the data capture code improved, of course!). In any case it would be good for pyuvdata to either "do the right thing" (whatever that is in this case?) or refuse to combine these mismatched datasets.  Either would be preferable to outputting invalid datasets.

**Comment by bhazelton** [comment]
thanks for this report @wfarah, we definitely need to fix this. @kartographer I think we should add the check you're suggesting and we should also check to see if this problem is present in the `add` methods of the other objects, which were based on this code.

**Comment by kartographer** [comment]
@bhazelton -- sounds good, I'll have a PR for someone to review in just a few minutes...

**Comment by kartographer** [comment]
@bhazelton -- taking a brief look through `UVFlag`, `UVBeam`, and `UVCal`, I think the answer to your question is "yes", although the code that's in `UVFlag.__add__` looks less mature and doesn't seem to do nearly as rigorous a job checking metadata as that for the other objects.

**Comment by bhazelton** [comment]
Ok, I'll make issues for those objects so they can be tracked separately.
