### ISSUE TITLE
Add apply_cal method to uvdata that takes in a uv cal object.

### ISSUE THREAD

**Issue by bhazelton** [RadioAstronomySoftwareGroup/pyuvdata#114]
Must write comment into history about what happened.

**Comment by adampbeardsley** [comment]
I've been working on this issue off and on lately. I have some of the basic code in place (see branch apply_cal), but wanted to open a few things up for converstation:
- Is an inplace (or not inplace) option wanted?
- I assume we want to support full jones calibration. Does anyone have any idea how to test this? I'm assuming we don't have any full-jones solutions lying around.
- When coding things up, it seemed natural to not bother forming mueller matrices if Njones <= 2  because they will just be diagonal, and it's easier to code the operation without the matrices. Are people ok with that?

**Comment by bhazelton** [comment]
We really need to make a new pyuvdata release, but that is blocking on this issue. How close are we on resolving this issue? If it's a long way off, I think we should consider making a new release even without this fixed.

**Comment by nkern** [comment]
Partially addressed by #629 but D-term calibration is not implemented

**Comment by bhazelton** [comment]
close in favor of #688
