### ISSUE TITLE
`SCALEFAC` / `BSCALE` is incorrect for mwa_corr_fits for observations after October 2014 

### ISSUE THREAD

**Issue by derwentx** [RadioAstronomySoftwareGroup/pyuvdata#1149]
Hey there,
when reading MWA corr fits files, pyuvdata makes an incorrect assumption about `SCALEFAC` [here](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/3bec5a5484d28e0ee4f05b579c9e8853af2ff968/pyuvdata/uvdata/mwa_corr_fits.py#L1337) . I expected `UV.extra_keywords['SCALEFAC']` to have a value of 0.125, but instead it had a value of 0.25, and incorrectly scaled the data.

Here's a demo: 
https://gist.github.com/derwentx/0c0a6df1ac5b1726764c4ca2fe688b86#file-pyuvdata_bscale-ipynb

version info:

```txt
sys.version_info(major=3, minor=10, micro=2, releaselevel='final', serial=0)
pyuvdata.__version__='2.2.8'
```

i'm using the latest pyuvdata main, sha `3bec5a5484d28e0ee4f05b579c9e8853af2ff968`

os info, `uname -a`:
```txt
Linux sirius 5.16.11-arch1-1 #1 SMP PREEMPT Thu, 24 Feb 2022 02:18:20 +0000 x86_64 GNU/Linux
```

**Comment by PyxieLouStar** [comment]
As far as I know, it is true that before October 2014 the data was divided by 4 and no `BSCALE` keyword was recorded.

My best guess as to what is happening here (I'll take a look at the data to confirm) is that `BSCALE` recorded in a different place than `mwa_corr_fits` is looking for it. `mwa_corr_fits` looks for `BSCALE` in the zeroth hdu, and in this case did not find it there. Looking at the attached notebook, `BSCALE` is recorded in the first hdu. My guess is that `BSCALE` is in the first hdu and not the zeroth. I'm not sure if this is due to a change that was made at some point in the correlator. It is a case that we should look for and handle correctly.

**Comment by PyxieLouStar** [comment]
Looking at a 2015 data file (1131733552), `BSCALE` is in all hdu headers, but in the 2019 data looked at by @derwentx (1254670392) `BSCALE` is in all but the zeroth hdu header. @gsleap do you know when this change took place?

**Comment by gsleap** [comment]
@PyxieLouStar in late 2017 there was work done to implement FITS HDU compression out of the correlator. It's possible that process resulted in no BSCALE in the Primary HDU.
