### ISSUE TITLE
Write measurement sets with both data and model visibilities

### ISSUE THREAD

**Issue by rlbyrne** [RadioAstronomySoftwareGroup/pyuvdata#1202]
MS files support both data and model visibilities, but the `write_ms` function only allows writing one of those. It would be useful to allow writing both.

**Comment by rlbyrne** [comment]
Likewise, it would be helpful to be able to write to the CORRECTED_DATA column

**Comment by kartographer** [comment]
@rlbyrne -- I might finally get around to this as part of #1391. Just to confirm, you're looking to (or rather, it's acceptable to) record these values all simultaneously rather than a sort of "partial write" scenario? The former should be straightforward to do, but the latter may require some additional heavy lifting.

**Comment by kartographer** [comment]
@rlbyrne -- I've now got a solution for this integrated into #1391 if you want to give it a spin and give any feedback.
