### ISSUE TITLE
MWA Measurement Sets with UT1 are not supported

### ISSUE THREAD

**Issue by d3v-null** [RadioAstronomySoftwareGroup/pyuvdata#1248]
Hey there,
The MWA stack (Birli, Hyperdrive, ASVO) have recently moved to writing the TIME column for measurement sets in the UT1 frame by default instead of UTC. 

Pyuvdata does not take into account the metadata for the TIME column which specifies which time frame is being used when reading measurement sets

Here's an example of a file in the new format: https://github.com/MWATelescope/mwa_hyperdrive/tree/main/test_files/1090008640 

```
from astropy.time import Time
from casacore.tables import table
tb_main = table("1090008640_birli_trunc.ms")
time_arr = tb_main.getcol('TIME') / 86400.0
timescale = tb_main.getcolkeyword('TIME', 'MEASINFO')['Ref']
print(timescale) # -> UT1 (used to be UTC)
time_array = Time(time_arr, format='mjd')
print(time_array[0].gps, time_array[0].delta_ut1_utc) # -> 1090008641.6870422 -0.3129575685307169
```

The fix is pretty simple, just pass the timescale from the column metadata when creating the astropy Time object:

```
time_arr = tb_main.getcol('TIME') / 86400.0
timescale = tb_main.getcolkeyword('TIME', 'MEASINFO')['Ref']
time_array = Time(time_arr, format='mjd', scale=timescale.lower())
print(time_array[0].gps) # -> 1090008641.9999998
```

Here's the commit where we made this change if you'd like more details: https://github.com/MWATelescope/Marlu/commit/39551f0ed9e3e87c65968b0bcc1d455a9582ee18 

Cheers

**Comment by bhazelton** [comment]
Thanks for reporting this @d3v-null! I made a PR to fix this, comments are very welcome. I used one of the test files you pointed me to to test this and I added it to our test files for a unit test, but I just realized that may not be allowed under the license on that repo because it is a copy-left license and pyuvdata is licensed under a permissive BSD license. Can you provide me with a small test file to use instead that is not licensed under a copy-left license?
