### ISSUE TITLE
Reading and writing ms files does not preserve data

### ISSUE THREAD

**Issue by rlbyrne** [RadioAstronomySoftwareGroup/pyuvdata#1355]
I am testing a CASA-based calibration and imaging pipeline that accepts .ms files as input.

Directly inputting the .ms file (in this case from the OVRO-LWA) produces this image. The colorbar scale here is 0-70 (arbitrary units):
<img width="445" alt="Screenshot 2023-11-02 at 4 07 00 PM" src="https://github.com/RadioAstronomySoftwareGroup/pyuvdata/assets/12840057/80cfe36e-edd3-4e3b-a2ea-b53c8a98f0ec">

Next, I've tried reading the .ms file in pyuvdata and immediately rewriting it with these commands:
`uv.read_ms("20230819_093023_73MHz.ms")`
`uv.write_ms("20230819_093023_73MHz_rewritten.ms")`
Now using the exact same calibration and imaging pipeline with the new .ms file gives this image (colorbar scale 0-400):
<img width="445" alt="Screenshot 2023-11-02 at 4 03 00 PM" src="https://github.com/RadioAstronomySoftwareGroup/pyuvdata/assets/12840057/06d2c4f4-d694-411b-8932-c153f5950065">

It looks like many visibilities are being flagged by CASA's calibration. The bottom line is that the `read_ms` and `write_ms` commands do not preserve the .ms file.

**Comment by rlbyrne** [comment]
Update: At least part of the problem is the baseline conjugation. Setting `run_check=False` substantially improves the calibrated image. Here is the resulting image with the same colorbar scale as the first image above.
<img width="440" alt="Screenshot 2023-11-10 at 12 03 53 PM" src="https://github.com/RadioAstronomySoftwareGroup/pyuvdata/assets/12840057/a79d440b-479c-4352-8888-d25677c8ffe0">
However, even with `run_check=False` the image doesn't exactly match that of the raw .ms file. A side-by-side comparison is here. The image on the left is the rewritten file and the one on the right is the original.
<img width="1486" alt="Screenshot 2023-11-10 at 12 33 44 PM" src="https://github.com/RadioAstronomySoftwareGroup/pyuvdata/assets/12840057/ff9f1283-fc70-47be-92ca-283968358ba1">

**Comment by rlbyrne** [comment]
Running `uv_obj.reorder_pols(order="CASA", run_check=False)` solves this problem. Thank you to @kartographer for all the help with this! I know have a functioning workaround, but it would be great if these fixes could be integrated into the code so they won't trip up the next user. Maybe the reordering should occur automatically in the `write_ms` function?

**Comment by kartographer** [comment]
To put a little bit of additional context here, what was exposed here weren't pyuvdata bugs, per se, but rather some "features" of particular subtasks in CASA processing, in particular:

- The _uvw_-conjugation for some tasks being _apparently_ different (in particular, it seems as though the way we are writing it is correct for `tclean`, but perhaps incorrect for some other tasks).
- The polarization order needing to be in "CASA" (XX, XY, YX, YY) order versus AIPS order (XX, YY, XY, YX).

The latter is relatively easy to enforce. The former we can add a switch for, but it would be good to understand/document more thoroughly what it is we think is happening here, especially since we seem to be getting conflicting results for different use cases. @bhazelton -- a little bit of crowdsourcing here might be particularly useful, if we can round up the users.

**Comment by rlbyrne** [comment]
@kartographer I'm using known bright sources
