### ISSUE TITLE
carrying input filename attribute with UVData object, as well as a name attribute

### ISSUE THREAD

**Issue by nkern** [RadioAstronomySoftwareGroup/pyuvdata#319]
Can we include two more non-required attributes for a `UVData` object? 

The first I'd like is a string-type `filename` attribute, which would be the filename if one used a `read_*` function. This would not be a required parameter b/c one could create a `UVData` object from scratch, in which case there is no appropriate filename attribute. This would be useful information for `hera_pspec` to propagate so that we know exactly which file was crossed with which file when forming power spectra.

The second would be a string-type `name` attribute, which would a way to give each UVData object a useful name depending on what we are doing with the data. For example when we start to make various jackknife groups, we will be selecting out subsets of UVData objects, and it would be nice to assign a `name` to each selection to propagate through to the power spectrum object so its easy to know what the underlying data represents.

**Comment by bhazelton** [comment]
These can both be done using the existing `extra_keywords` attribute -- these can be anything that isn't a string, list, or object and they are fully propagated into & out of files when the object is read/written. Does that meet the need?

**Comment by nkern** [comment]
Ah yes, that would be great! But what do you mean by "anything that isn't a string, list, or object", I want these to be string-type variables..

**Comment by bhazelton** [comment]
Sorry, that was a typo. I meant anything other than an array, list or object. Strings are fine.

**Comment by bhazelton** [comment]
Sure, feel free to make the PR. My instinct would be to make it optional and not on by default. This is the first request for something like this, so it's not clear that the general user wants it, but I'm happy for others to weigh in.

You should probably do the same thing for the UVCal and UVBeam objects, we're trying to keep a fair amount of symmetry between them.

There's also an issue around how to handle combined data (where you read in multiple files). If you don't handle that explicitly, there'll be errors because the extra keywords don't match between the objects. You'll need to have some testing around this issue.

**Comment by bhazelton** [comment]
@nkern is this still something you want?

**Comment by bhazelton** [comment]
How should this be propagated through file read/writes?

**Comment by bhazelton** [comment]
Should *not* be round-tripped through file write/read.
