### ISSUE TITLE
Convenience method for extracting redundant baseline groups

### ISSUE THREAD

**Issue by philbull** [RadioAstronomySoftwareGroup/pyuvdata#417]
It would be very useful to have a method on `UVData` objects that can retrieve a list of baselines within a redundant group. We have a few different custom functions to do this already -- one in `hera_cal` and one in `hera_pspec` I believe -- but it would be useful to have this as part of `UVData` to avoid needing to maintain this functionality externally.

For reference, the implementations we currently have select redundant baselines based on antenna separation and angle, within some tolerance.

**Comment by nkern** [comment]
There are a few methods in `hera_pspec` to do this already. The relevant one for `pyuvdata` might be to copy over parts of `hera_pspec.utils.get_reds`, which itself uses `hera_cal.redcal.get_pos_reds`

**Comment by jsdillon** [comment]
This would be pretty trivial to implement in `hera_cal.io.HERAData`, which subclasses hera_data and knows about the antenna positions in a dictionary that is compatible with `hera_cal.redcal.get_pos_reds`.

**Comment by bhazelton** [comment]
@nkern @aelanman it sounds like the two of you might be well-placed to make this happen and like it would be useful on several separate fronts, so it would be a good addition to the UVData object. Are you willing & able to take it on?

**Comment by aelanman** [comment]
@bhazelton I've contacted Nick and started working on a new branch to implement this. I've written a function that will find redundancies from the baseline vectors, and am working on a unit test for it.

**Comment by bhazelton** [comment]
great! Let me know when/if I can be helpful.

**Comment by aelanman** [comment]
@nkern  I decided to write something from scratch instead of copying over from `hera_pspec` and `hera_cal`. This method just uses the numpy `unique` function to a given precision to identify redundancies in the full baseline vector (ie., not just by length). For the unit test to be useful, ideally I'd have a test file with _nearly_ redundant baselines that are known. Then I can test that baselines are redundant as expected with different levels of precision. Right now I'm using a perfectly-redundant hera19 simulation file for testing.

**Comment by bhazelton** [comment]
Maybe once you have this written you can test it against the inputs to hera_pspec or hera_cal and see whether it performs the same way. That would be a nice outside test of the code.

**Comment by bhazelton** [comment]
@nkern @philbull Adam's first pass at implementing this has been merged in. Can you two take a look and see if it achieves what you want?

**Comment by bhazelton** [comment]
@nkern @philbull I believe this issue has been addressed now, so I'm closing it. I'd love you to try it out and give us feedback and feel free to make a new issue for any changes you'd like to see.

**Comment by jsdillon** [comment]
I'm a bit confused why we want to treat baselines with uvws that are equal and opposite as not redundant. Won't that lead to us simulating up to twice the number of baselines we actually need to simulate?

**Comment by aelanman** [comment]
The default behavior is to find redundancies among the baselines present in the file, as this is the simplest thing to calculate. You're right though. When simulating, it will make more sense to use `with_conjugates`.

**Comment by bhazelton** [comment]
That was the initial implementation, but that has been changed in a recent PR. If you take a look at the methods involved, `utils.get_baseline_redundancies` has a `with_conjugates` keyword that will give you back redundancies including the conjugates, as well as a list of which baselines you need to conjugate to get them to match. The antenna-based function `utils.get_antenna_redundancies` just gives you all the redundancies (because there's no intrinsic direction as there is with baselines that are already defined).
