### ISSUE TITLE
Update documentation to clarify what `integration_time` and `nsample_array` mean

### ISSUE THREAD

**Issue by plaplant** [RadioAstronomySoftwareGroup/pyuvdata#445]
We should make it clear to users what the precise meaning behind these arrays are. Updating the docstrings should be sufficient, so the information gets automatically propagated to readthedocs.

**Comment by bhazelton** [comment]
Key points:
1: the product of the integration time and the nsample array value for a visibility reflects the total amount of time that went into the visibility.
2: The integration time should reflect the length of time a visibility was integrated over, so should be a way to do selections for differently integrated baselines following BDA (baseline-dependent averaging). This is useful because the integration time is in the metadata and can be read very easily and used for selections.
3. The previous points imply that the function of the nsample array is to track flagging within an integration time (leading to a decrease of the nsample array value) and LST averaging (leading to an increase in the nsample array value). So datasets that have not been LST averaged should have nsample array values less than or equal to 1.

**Comment by bhazelton** [comment]
Note that these are guidelines, some files coming into pyuvdata may have different conventions for points 2 & 3. Point 1 is generally true.
