### ISSUE TITLE
Reorder polarization axis in _key2inds for conjugate data when cross pols are present

### ISSUE THREAD

**Issue by plaplant** [RadioAstronomySoftwareGroup/pyuvdata#478]
When using functions like `get_data` that call `_key2inds`, requested baselines whose conjugation is present in the data are properly conjugated. (E.g., if the file contains baseline (0, 1), but the user requests (1, 0), then the visibility data for (0, 1) is returned with a conjugation.) However, when cross-polarizations are present, the polarization should also be reordered (e.g., xy and yx should be swapped), so that the returned array's polarization axis has the same convention as the `polarization_array` contained in the UVData object. The calculation of the polarization array for conjugated data in `_key2inds` should be changed (e.g., here: https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/master/pyuvdata/uvdata.py#L2616), which should make everything downstream "just work".

**Comment by adampbeardsley** [comment]
I'm going to give this a go this morning. A couple comments/questions:

- Just to clarify, this bug was fixed for the case when the user requests a specific polarization, but we missed the case when the user wants _all_ the polarizations. In other works, `uv.get_data((1, 0, 'xy'))` should work, but `uv.get_data((1, 0))` will return the data in the wrong polarization order.

- What do we want to do in the case where the data only has one cross pol. For example, an `xy` file that has baseline `(0, 1)`, but the user asks for baseline `(1, 0)`? I think the right thing is to return empty (or maybe an error, I'll check what we do when you ask for a non-existent baseline). It seems a little odd because you can ask for `(1, 0)` in two cross-pol files and get errors, but when you ask for the same thing in a combined file you get data. c'est la vie? @plaplant @bhazelton do you have an opinion?

- @bhazelton I think this should be considered a bug fix, but it will change the output users get. So I'm not sure how you want to handle this as far as versions/subversions/etc.

**Comment by plaplant** [comment]
@adampbeardsley re: bullet point 2, I agree that an error/empty is a good solution. It's better than feigning it's the right thing, and if the user _really_ wanted `(1y, 0x)`, they could explicitly ask for it using the 3-tuple key.

**Comment by bhazelton** [comment]
I agree on bullet 2.

On 3, we do not do semantic versioning, so we don't have to worry about changing version numbers around this. What we try to do is not change the API or behavior in a way that makes existing users get errors or unexpected results without a deprecation warning period. I think this is a bug fix -- I don't think there's anyone who expects the behavior that is currently happening.

**Comment by bhazelton** [comment]
But please do add a short description in the changelog so people can know when it was fixed.
