### ISSUE TITLE
uv beam frequency interpolation with new object returns tuple

### ISSUE THREAD

**Issue by samanthamcgraw** [RadioAstronomySoftwareGroup/pyuvdata#622]
calling _interp_freq with new_object=true gives a tuple with a uv beam object as the zeroth entry and 'None' as the first entry. Is this the desired behavior?

**Comment by bhazelton** [comment]
It is expected, that's explicitly stated in the returns section of the docstring: https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/master/pyuvdata/uvbeam.py#L753

Note that this method starts with an underscore, indicating that it is a private method. Private methods are not considered to be part of the API, so no guarantees are made about keeping interfaces fixed. If it turns out that this is a method that is being used a lot, we should look at ways to get the functionality available through a public method.

**Comment by bhazelton** [comment]
After talking to @jpober about this more, I can see the confusion about the return and why you need to use this function (in order to get a new UVBeam object). I think we need a better approach for that situation, I'll leave this issue open while we figure out what it should be.
