### ISSUE TITLE
get_antenna_redundancies fails to properly group North-South oriented baselines.

### ISSUE THREAD

**Issue by zacharymartinot** [RadioAstronomySoftwareGroup/pyuvdata#650]
This example demonstrates the issue:

```python
import numpy as np
import pyuvdata
import matplotlib.pyplot as plt

eps = 1e-10 # the size of the error induced by pyuvdata ENU <-> ECEF transformations

# antenna positions at corners of a square with two small perturbations
ant_pos = np.array([
    [-eps,1.,0.],
    [1.,1.,0.],
    [eps,0.,0.],
    [1.,0.,0.]
])

ant_nums = np.arange(4)

red_grps, _, _ = pyuvdata.utils.get_antenna_redundancies(ant_nums, ant_pos, tol=0.1)

for grp in red_grps:
    bl_num = grp[0] # get one baseline from each redundant group
    ai, aj = pyuvdata.utils.baseline_to_antnums(bl_num, 4)
    bij = ant_pos[aj] - ant_pos[ai]
    
    plt.plot(bij[0], bij[1], '.k', ms=10)
plt.ylim(-1.1,1.1)
plt.xlim(-1.1,1.1)
plt.show()
```
produces this figure of baseline positions for this demo array

![redundancy_group_failure](https://user-images.githubusercontent.com/13594524/62745625-e7f43200-ba19-11e9-9787-c3a7420425cc.png)

`red_grps` has 5 groups when there are really only 4. The points at (0, 1) and (0, -1) should be in the same redundant group. This looks like a problem with the initial attempt in `get_antenna_redundancies` to select only half the points.

**Comment by jaguirre** [comment]
Doesn’t the version in hera_cal deal with this correctly?  Is the right thing to merge in the hera_cal implementation?

James Aguirre
Associate Professor
Department of Physics and Astronomy
University of Pennsylvania
David Rittenhouse Laboratory 4N4b
209 South 33rd Street Philadelphia, PA 19104
(215) 898-9596 (office)
(215) 898-9646 (lab)
jaguirre@sas.upenn<mailto:jaguirre@sas.upenn>.edu
http://www.sas.upenn.edu/~jaguirre/

**Comment by aelanman** [comment]
This seems to be an issue with the baseline conjugation at the start of `get_antenna_redundancies`:

```
            bv = antenna_positions[aj] - antenna_positions[ai]
            # Enforce u-positive orientation
            if (bv[0] < 0 or ((bv[0] == 0) and bv[1] < 0)
                    or ((bv[0] == 0) and (bv[1] == 0) and bv[2] < 0)):
                bv *= (-1)
```
In your example, baseline `(0,2)` is deemed to be u-positive because its u component is larger than zero (albeit, by epsilon). Baseline `(1,3)`, however, is not u-positive because its u==0 but its v < 0, so this one gets flipped to `(3,1)`. The expectation, though, is that this will 

This is only really an issue for baselines that are almost identically North-South. I think the solution is to replace the equality checks in the above code with `numpy.isclose()` statements.

**Comment by aelanman** [comment]
Looking more closely, in this case it looks like the problem is that a baseline with very small negative u is being flipped, when the expectation is that its u component is effectively zero so the check should look to the v component to determine if it needs to be flipped or not.

I'm not sure of the best way to fix this. The fix ought to be to the lines I referenced before, where it's checking baseline orientations and ensuring consistency.

If I change `bv[0] < 0` to `bv[0] + 1e-9 < 0`, then you get the right groupings:

![groups](https://user-images.githubusercontent.com/12849618/62749335-07935680-ba2a-11e9-8c9c-d0313037d597.png)

**Comment by bhazelton** [comment]
@aelanman do you have any insight here?
