### ISSUE TITLE
Testing speed up

### ISSUE THREAD

**Issue by mkolopanis** [RadioAstronomySoftwareGroup/pyuvdata#800]
More of a note for myself to look into, but can we use asynchronous testing to speed up the UVBeam testing. If we can push the beam healpix conversion to the background while other tests are executed this may help with testing times.
https://github.com/pytest-dev/pytest-asyncio

**Comment by plaplant** [comment]
I think we might actually want to use parallel testing using [pytest-xdist](https://pypi.org/project/pytest-xdist/), rather than `pytest-asyncio`. I've toyed around with it locally doing, e.g., `pytest -n 8`, but gotten mixed results, largely because of file I/O issues. I think we'd have to move to using temporary directories for all I/O tests rather than writing files to the `data/test` directory, like we do now. But I'm definitely on board--if we can get it to work reliably, I think we can really speed up our test times.

**Comment by mkolopanis** [comment]
yeah very interesting, this does seem like a better solution. There are temp directory fixtures build in to pytest too so the conversion should be "easy".

**Comment by mkolopanis** [comment]
Looks like github action runners have a 2-cpu setup. Which would still provide some level of increase compared to single threading.

**Comment by mkolopanis** [comment]
I'm looking into this a bit, starting with the temp_path fixture in pytest, but the miriad segfaults are popping up again.

**Comment by plaplant** [comment]
Since the last time I fought with miriad segfaults, I realized we should probably define a private `_close()` method on the `Miriad` object that has a corresponding C++ function call that will flush and close the file. Right now it's only done when python calls the object's destructor, which the user has no control over. (Hence our current approach of "call `del`, run garbage collection, and cross our fingers it's actually closed.") We can then call that `_close()` method at the end of `write_miriad`, which (I hope) will prevent this segfault issue.

I'll take a quick stab at such a function definition, though I'm not sure of a robust way to test it besides removing the current song-and-dance from miriad tests and seeing if CI works...

**Comment by mkolopanis** [comment]
If this temp stuff can reliably produce them I'd love to try that out paired with this update. That would inspire confidence for me at least, but yeah not really a way to definitively test it.

**Comment by plaplant** [comment]
PRs #813 and #815 have significantly sped tests up and implemented `pytest-xdist`, so tests typically take less than 10 minutes per job now. There are probably some further improvements we could make, but I think we've made enough progress to close this issue for now.
