### ISSUE TITLE
Rewrite miriad interface using Cython/CFFI

### ISSUE THREAD

**Issue by plaplant** [RadioAstronomySoftwareGroup/pyuvdata#812]
Right now, we are interfacing with the underlying miriad routines using a series of hand-written wrapper functions using the [Python/C API](https://docs.python.org/3/c-api/index.html). While this has worked well on the whole, there are some corner cases (like properly closing files) where the handling of the objects can yield segmentation faults or other bits of user-unfriendliness. In particular the reference counting seems to be incorrect, and tracking down how it should be done is likely non-trivial.

One possible solution is to rewrite the miriad interface using [Cython](https://cython.readthedocs.io/en/latest/) or [CFFI](https://cffi.readthedocs.io/en/latest/), which (to my understanding) are ways to access the functionality of compiled C code without having to do reference counting or explicit interface function building by hand. Either of these options is likely a large amount of work, but would lead to more stability of the miriad interface. I haven't personally used either of these options in non-trivial cases, so any expertise or guidance in this area would be most appreciated.

**Comment by steven-murray** [comment]
I've used CFFI a bit in 21cmFAST (but only bordering on non-trivial, really). It's pretty nice. Typically what you want to do is write a set of nice functions on the C-side which are listed in a header, and that will become the "API" that interfaces with python. Everything's easy from there. Also, any memory that you want to access from python should probably be created with python and passed as pointer to C, rather than the other way round. It's just easier that way.

**Comment by mkolopanis** [comment]
I ended up picking a cython solution to this problem, but CFFI does sound interesting. I do not think the base C code is "set up nicely" for a CFFI type connection.
