### ISSUE TITLE
Remove freq_array for delay type calibration

### ISSUE THREAD

**Issue by jpober** [RadioAstronomySoftwareGroup/pyuvdata#850]
For delay type calibration, no frequency array should be required and Nfreqs should be equal to 1 (so we don’t lose an entire axis and have the gain_array change dimensionality).  When you convert from delay to gain you should then need to pass in a freq_array.  freq_range is probably OK to keep, but should never be required and should indicate in the docs that it should only be used for delay type.  Flag array should also enforce Nfreqs = 1 when delay type is used.

**Comment by bhazelton** [comment]
The implementation in #1034 is slightly different than that proposed here because we're also adding support for wide-band gain solutions (only if future_array_shapes is True). Delay solutions are always wide-band. For wide-band solutions, Nfreqs must be 1, the freq_array is not required and the freq_range is required. The freq_range parameter is also getting an spw axis so that it can contain the freq range for all the spectral windows.
