### ISSUE TITLE
Consider making `put_*` methods matching `get_*` methods

### ISSUE THREAD

**Issue by bhazelton** [RadioAstronomySoftwareGroup/pyuvdata#886]
A request form James, needs more thinking.

**Comment by bhazelton** [comment]
closely related to #910

**Comment by plaplant** [comment]
We decided that it would probably be good practice to have `put_`/`set_` methods paralleling all of the `get_` methods. We also decided that in the case that the user-provided array does not match the shape/dimensionality of the target array, we would raise an error rather than silently broadcasting (e.g., the user provides a time/frequency waterfall, but the `get_data` shape matches polarization as well).
