### ISSUE TITLE
Adding support for future array shapes in UVBeam objects

### ISSUE THREAD

**Issue by kartographer** [RadioAstronomySoftwareGroup/pyuvdata#914]
Following the merge of #909, `UVBeam` objects and methods now need to be updated to allow for the new handling of multiple spectral windows, and more generally to allow for the proper handling of the flexible spectral window feature found in `UVData`.

**Comment by bhazelton** [comment]
I’m working on `future_array_shapes` and `flex_spws` for UVBeam. I think I’ve got all the future array shapes parts worked out, so I started thinking about flexible spws. The more I think about it, the less clear it is to me that it is a useful concept on UVBeam.

The UVBeam object has a `freq_array`, but it doesn’t have a `channel_width` because that’s not a very sensible concept for simulations (or measurements) of beam responses — they’re generally just at a particular frequency. One of the most widely used methods on UVBeam is interpolation (both in frequency and spatially). When I started trying to think about how interpolation in frequency should interact with spectral windows I realized that I don't really know that spectral windows is a useful concept on UVBeam.

I'd love to hear thoughts about what utility spectral windows provides for UVBeam objects.

**Comment by bhazelton** [comment]
A suggestion from @kartographer is to not implement any `flexible_spw` related code but also just make the existing `spw_array` and `Nspws` parameters optional rather than removing them in case we wanted to implement something similar to the `wide_band` mode of UVCal in the future to describe beam models that are valid over a range of frequencies.
