### ISSUE TITLE
sum_vis requires object_name to be the same

### ISSUE THREAD

**Issue by jpober** [RadioAstronomySoftwareGroup/pyuvdata#920]
We're trying to add the visibilities from a pyuvsim simulation of the GSM and a pyuvsim simulation of GLEAM.  sum_vis is erroring because object_name is different.  I can see the rationale for not adding visibilities from different fields on the sky but it's obviously not what we want here.  So we either need to change this behavior in the sum_vis method (i.e. remove object_name from the compatibility parameters list, or at least add the option to ignore it and/or replace it with a new value) or have pyuvsim use object_name differently.

**Comment by ntk688** [comment]
That list of parameters might be pretty draconian in general. The only ones not included are data_array and history at the moment. Are there other parameters there that people might want to override, like extra_keywords for instance? If so, we could add a keyword (defaulted to false) to override a certain set of checks, or just raise warnings about them? 

The other decision to be made is what new value to add to metadata elements that did not match. Leave some string that indicates that two objects with different object_name were added?

**Comment by bhazelton** [comment]
I agree that object_name being different is basically never an issue because the phasing already has to be identical. So we can remove it from the compatibility list and decide what to set it to if there are different values. Are there other parameters in the list we should handle the same way? I think extra_keywords should be allowed to be different (although if they have the same keys with different values I'm not sure what we should do).

Then there are things that probably should not be different in the general case, but we might want to let people override if they really want to. We could add a keyword that could take a list of parameters to ignore, I suppose.

**Comment by bhazelton** [comment]
For object name, combine the values as strings for the default.
For extra keywords, combine unless there's a collision, otherwise warn and take the first one.

Maybe also an optional keyword that takes a dict with parameter names and values to overwrite.
